Feature/expense
markotny/save-app pull request #32
Opened 2020-06-01 15:50 UTC by jandlu08

2020-06-02 15:05 UTC, markotny requested changes
Pała, siadaj

2020-06-02 15:05 UTC, markotny commented on src/app/modules/categories/categories.service.ts
> +export class CategoriesService {
ten serwis jest do czegoś potrzebny? chyba ni

2020-06-02 15:05 UTC, markotny commented on src/app/modules/categories/categories/categories.component.ts
> +      this.activeBudget$.subscribe(o => (this.activeBudget = o))
Co to za rak, o async pipe nie słyszał? xd

2020-06-02 15:05 UTC, markotny commented on src/app/modules/categories/categories/categories.component.scss
> +  font-family: Montserrat, serif;
tu chyba nie ta czcionka, nie zgadza się z resztą widoków

2020-06-02 15:05 UTC, markotny commented on src/app/modules/categories/categories/categories.component.html
> +      <ng-template pTemplate="body" let-category>
na liście wszystkich kategorii też powinny być te same akcje dostępne co na liście od aktywnego budżetu, bo inaczej nie ma możliwości edycji/usunięcia kategorii, która nie jest przypisana do żadnego budżetu

2020-06-02 15:05 UTC, markotny commented on src/app/modules/expense/activebudget-expenses/activebudget-expenses.component.html
> +            <a class="pi pi-paperclip" (click)="showDetails(expense)"></a>
Spinacz raczej kojarzy się z załącznikiem niż wyświetlaniem szczegółów (tym bardziej, że w przyszłości zakładamy możliwość dodawania załączników do wydatków) - sam musiałem do kodu popatrzeć żeby się zorientować że to tutaj się szczegóły wyświetla. Lepiej by było otwierać szczegóły po kliknięciu na cały wiersz po prostu (oprócz ostatniej kolumny z akcjami)
W wersji mobilnej z resztą szczegóły są po kliknięciu w nazwę to mogło by to tutaj chociaż tak samo działać

2020-06-02 15:05 UTC, markotny commented on src/app/modules/incomes/activebudget-incomes/activebudget-incomes.component.html
> +          <th>Date of expense</th>
income nie expense

2020-06-02 15:05 UTC, markotny commented on src/app/modules/incomes/activebudget-incomes/activebudget-incomes.component.html
> +          <th>Category</th>
income nie ma kategorii

2020-06-02 15:05 UTC, markotny commented on src/app/modules/expense/mobile-expense-details/mobile-expense-details.component.html
> +  <div>{{expense.categoryId}}</div>
Dlaczego tu się wyświetla ID kategorii?
To samo poniżej z ID budżetu.
Analogicznie w income details

2020-06-02 15:05 UTC, markotny commented on src/app/modules/expense/mobile-expense-details/mobile-expense-details.component.html
> +  <div>{{expense.amount}}</div>
amount powinno wyświetlać currency budżetu.
Analogicznie.. wszędzie xd

2020-06-02 15:05 UTC, markotny commented on src/app/modules/expense/activebudget-expenses/activebudget-expenses.component.html
> +          <td>{{ expense.categoryId }}</td>
Powinna tu być nazwa kategorii

2020-06-02 15:05 UTC, markotny commented on src/app/modules/expense/activebudget-expenses/activebudget-expenses.component.html
> +          <td>{{ expense.amount }}</td>
Fajnie by było gdzieś wyświetlić currency. Jeśli nie w każdym wierszu to może chociaż w nagłówku kolumny

2020-06-02 15:05 UTC, markotny commented on src/app/modules/categories/categories/categories.component.ts
> +  activeCategories$ = this.store.select(CategorySelectors.activeBudget);
Tu powinno być CategorySelectors.activeBudgetSums

2020-06-02 15:05 UTC, markotny commented on src/app/core/core.module.ts
> +    TableModule,
od tego jest SharedModule, a nie Core

2020-06-02 15:05 UTC, markotny commented on src/app/modules/incomes/incomes-details/incomes-details.component.ts
> +  editExpense(item: Income) {
Nazwy metod się nie zgadzają ale pomijając już to, może lepiej by było zrobić po prostu jeden wspólny layout dla expense i income? Ale no to jeszcze rozumiem bo na szybko było robione

2020-06-02 15:05 UTC, markotny commented on src/app/state/categories/categories.selectors.ts
> +  ExpenseSelectors.activeBudgetGroupedSums,
jakaś pozostałość po 10 merdżach, usuń tą linijkę

2020-06-02 15:05 UTC, markotny commented on package.json
> +    "@fullcalendar/core": "^4.4.2",
Jest używane gdzieś cokolwiek z tej paczki?

I inna sprawa, jest jakiś powód dla którego postanowiłeś pozbyć się package-lock.json? xd

2020-06-02 15:05 UTC, markotny commented on src/app/modules/incomes/incomes-details/incomes-details.component.html
> +    <div><b>Budget:</b> {{income.budgetId}}</div>
id..

2020-06-02 15:05 UTC, markotny commented on src/app/modules/incomes/activebudget-incomes/activebudget-incomes.component.ts
> +    this.subscriptions.push(this.incomeList$.subscribe(o => this.incomeList = o));
rak nieborak

2020-06-02 15:05 UTC, markotny commented on src/app/modules/incomes/activebudget-incomes/activebudget-incomes.component.html
> +          <td>{{ income.categoryId }}</td>
¯\\\_(id)\_/¯

2020-06-02 15:05 UTC, markotny commented on src/app/modules/expense/expense-details/expense-details.component.html
> +    <div><b>Category:</b> {{expense.categoryId}}</div>
..id

2020-06-02 15:09 UTC, bartoszprokopowicz commented on src/app/modules/expense/activebudget-expenses/activebudget-expenses.component.html
> +            <a class="pi pi-paperclip" (click)="showDetails(expense)"></a>
Jak reszta jest git to tutaj muszę stwierdzić, że Janusz zrobił wedle design'u w adobe xd. Co do twojej propozycji to jestem za, lepiej to będzie działać myślę. Ogólnie to dzisiaj siadam jakoś po 19 i jeszcze to popoprawiam. Do 23 postaram się to wystawić w wersji ostatecznej.

2020-06-12 17:05 UTC, jandlu08 commented on package.json
> +    "@fullcalendar/core": "^4.4.2",
jest, bo wywala errora bez niej xd, a powód dla którego pozbywłem się package lock to to, że npm i się jebał, a przypadkowo zacommitowałem

2020-06-14 10:29 UTC, markotny commented on src/app/modules/expense/activebudget-expenses/activebudget-expenses.component.html
> +          <td>{{ expense.amount }} {{expense.currencySymbol}}</td>
wykorzystaj pipe currrency

2020-06-14 14:17 UTC, markotny approved these changes
ni ma to jakieś piękne ale no działo

2020-06-15 17:15 UTC, merged